### ISSUE TITLE
Splash Screen

### ISSUE THREAD

**Issue by MuhamadSelim** [scalafx/ScalaFX-Tutorials#1]
How can I add a splash screen to my application using another stage besides primaryStage

**Comment by jpsacha** [comment]
There is a JavaFX example of doing that: https://gist.github.com/jewelsea/2305098. It can be ported to ScalaFX. Basically it is using the `PrimaryStage` (stage passed in as argument to start() in JavaFX) as the splash screen. When initial activities are completed, it creates a new Stage, hides `PrimaryStage`, and shows that new Stage.

**Comment by jpsacha** [comment]
I added a new splash-demo based on JavaFX example mentioned above.
