### ISSUE TITLE
Jars for scalafx

### ISSUE THREAD

**Issue by roncoleman125** [scalafx/ScalaFX-Tutorials#4]
I'm not at all proficient at using the build tools and would just like to give scalafx a try. Can you tell me how to find the primary jar(s) and all the dependency jars? I'm using Intellij.

**Comment by jpsacha** [comment]
You can open any of the `build.sbt` files in IntelliJ as a project (assuming that you have Scala plugin installed). It will add all needed dependencies. If you want to do it by hand here is the minimum list. 
```
org.scalafx:scalafx_2.13:16.0.0-R24
org.openjfx:javafx-base:16
org.openjfx:javafx-controls:16
org.openjfx:javafx-fxml:16
org.openjfx:javafx-graphics:16
org.openjfx:javafx-media:16
org.openjfx:javafx-swing:16
org.openjfx:javafx-web:16
```
For all JavaFX dependencies you will also need to add platform specific (for instance for Windows).

The build script handles all that for you. SBT is the default build system for Scala, it is worth knowing the basics if you program in Scala. See also this blog post for explanation: https://codingonthestaircase.wordpress.com/2013/05/17/getting-started-with-scalafx-compile-and-run-2/
